In [1]:
from google.colab import files
datafile = files.upload()

Saving Churn_Modelling.csv to Churn_Modelling.csv


In [4]:
import pandas as pd
df = pd.read_csv('Churn_Modelling.csv')

In [5]:
df.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [6]:
df['Exited'].unique()

array([1, 0])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [8]:
x = df.iloc[:,3:13].values
y = df.iloc[:,13].values

In [9]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [10]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [11]:
import numpy
numpy.unique(x[:,1])

array(['France', 'Germany', 'Spain'], dtype=object)

In [12]:
import numpy
numpy.unique(x[:,2])

array(['Female', 'Male'], dtype=object)

In [13]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [14]:
le = LabelEncoder()

In [15]:
x.shape

(10000, 10)

In [16]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [17]:
x[:,1]  = le.fit_transform(x[:,1])

In [18]:
x.shape

(10000, 10)

In [19]:
x

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [20]:
x[:,2]  = le.fit_transform(x[:,2])

In [21]:
x.shape

(10000, 10)

In [22]:
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [23]:
lst = []
sum = 0
for i in range(0,10):
    lst.append(len(numpy.unique(x[:,i])))
for i in lst:
    sum= sum+ i
print(sum)

16935


In [24]:
len(numpy.unique(x[:,2]))

2

In [25]:
x.shape

(10000, 10)

In [28]:
onehotencoder = OneHotEncoder()

In [29]:
x = onehotencoder.fit_transform(x).toarray()

In [30]:
x.shape

(10000, 16935)

In [31]:
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [32]:
x = x[:,1:]

In [33]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x1 = sc.fit_transform(x)

In [34]:
x1.shape

(10000, 16934)

In [35]:
x1

array([[-0.0100005, -0.0100005, -0.0100005, ..., -0.0100005, -0.0100005,
        -0.0100005],
       [-0.0100005, -0.0100005, -0.0100005, ..., -0.0100005, -0.0100005,
        -0.0100005],
       [-0.0100005, -0.0100005, -0.0100005, ..., -0.0100005, -0.0100005,
        -0.0100005],
       ...,
       [-0.0100005, -0.0100005, -0.0100005, ..., -0.0100005, -0.0100005,
        -0.0100005],
       [-0.0100005, -0.0100005, -0.0100005, ..., -0.0100005, -0.0100005,
        -0.0100005],
       [-0.0100005, -0.0100005, -0.0100005, ..., -0.0100005, -0.0100005,
        -0.0100005]])

In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x1, y, test_size = 0.2)

In [37]:
X_train.shape

(8000, 16934)

In [38]:
X_test.shape

(2000, 16934)

In [39]:
import keras

In [40]:
from keras.models import Sequential
from keras.layers import Dense

In [48]:
classifier = Sequential()

In [49]:
classifier.add(Dense(units = 6, kernel_initializer='uniform', activation='relu'))

In [50]:
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

In [51]:
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [52]:
classifier.compile(optimizer='adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [53]:
classifier.fit(X_train, y_train, batch_size = 10, epochs =15)

Epoch 1/15
800/800 [==============================] - 2s 2ms/step - loss: 0.5314 - accuracy: 0.7936
Epoch 2/15
800/800 [==============================] - 2s 2ms/step - loss: 0.4653 - accuracy: 0.7937
Epoch 3/15
800/800 [==============================] - 2s 2ms/step - loss: 0.4025 - accuracy: 0.7937
Epoch 4/15
800/800 [==============================] - 2s 2ms/step - loss: 0.3251 - accuracy: 0.7937
Epoch 5/15
800/800 [==============================] - 2s 2ms/step - loss: 0.2560 - accuracy: 0.8371
Epoch 6/15
800/800 [==============================] - 2s 2ms/step - loss: 0.2252 - accuracy: 0.8760
Epoch 7/15
800/800 [==============================] - 2s 2ms/step - loss: 0.2131 - accuracy: 0.8844
Epoch 8/15
800/800 [==============================] - 2s 2ms/step - loss: 0.2071 - accuracy: 0.8882
Epoch 9/15
800/800 [==============================] - 2s 2ms/step - loss: 0.2046 - accuracy: 0.8901
Epoch 10/15
800/800 [==============================] - 2s 2ms/step - loss: 0.2028 - accuracy: 0.8916

In [54]:
y_pred = classifier.predict(X_test)

In [55]:
y_pred = (y_pred>.5)

In [56]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1189  424]
 [ 177  210]]
